version: '3.7'
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: laithy/web
    ports:
      - '3001:3001'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: 'host'
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: laithy/api
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: 'host'
